# Generated by Django 5.1 on 2024-08-12 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('country', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('woman', 'woman')], max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('date_birth', models.DateField()),
                ('mobile', models.IntegerField()),
                ('years_exper', models.FloatField()),
                ('level', models.IntegerField(default=1)),
                ('ratings', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template4.categorie')),
                ('users', models.ManyToManyField(related_name='users', to='template4.prof')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template4.prof')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friends', to='template4.prof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='template4.prof')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('upload_at', models.DateTimeField()),
                ('size', models.FloatField()),
                ('image', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ManyToManyField(related_name='creaters', to='template4.prof')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('views', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template4.prof')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('description', models.CharField(default='', max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template4.prof')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('end', models.DateField()),
                ('description', models.CharField(default='', max_length=100)),
                ('client', models.CharField(default='', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='template4.categorie')),
                ('team', models.ManyToManyField(related_name='team', to='template4.prof')),
            ],
        ),
    ]
