# Generated by Django 5.1 on 2024-08-12 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template4', '0002_rename_prof_developper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='language',
            name='users',
        ),
        migrations.AddField(
            model_name='developper',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='template4.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developper',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='template4.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template4.developper'),
        ),
    ]
