# Generated by Django 5.1 on 2024-08-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template4', '0003_remove_job_user_remove_language_users_developper_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developper',
            name='lang',
        ),
        migrations.AddField(
            model_name='developper',
            name='lang',
            field=models.ManyToManyField(related_name='skills', to='template4.language'),
        ),
    ]
