# Generated by Django 5.1 on 2024-08-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template4', '0004_remove_developper_lang_developper_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
    ]
