# Generated by Django 5.1 on 2024-08-13 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template4', '0007_alter_friend_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developper',
            name='lang',
        ),
        migrations.AddField(
            model_name='language',
            name='dev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='template4.developper'),
            preserve_default=False,
        ),
    ]
